"""Add user_id to Analysis

Revision ID: 2f7ad7435783
Revises: d6795e16aab4
Create Date: 2026-07-19 16:12:27.617576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f7ad7435783'
down_revision: Union[str, None] = 'd6795e16aab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_analyses_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_analyses_user_id_users'), type_='foreignkey')

    # ### end Alembic commands ###
