"""Add ResumeGeneration and related tables

Revision ID: 50d62216ad35
Revises: d689298c47bb
Create Date: 2026-07-21 19:34:52.008593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d62216ad35'
down_revision: Union[str, None] = 'd689298c47bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_resume_id', sa.Integer(), nullable=True),
    sa.Column('target_role', sa.String(length=255), nullable=False),
    sa.Column('theme_choice', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('final_pdf_url', sa.String(length=1024), nullable=True),
    sa.Column('final_docx_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_resume_id'], ['resumes.id'], name=op.f('fk_resume_generations_source_resume_id_resumes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_resume_generations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_generations'))
    )
    with op.batch_alter_table('resume_generations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_generations_id'), ['id'], unique=False)

    op.create_table('resume_analysis_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generation_id', sa.Integer(), nullable=False),
    sa.Column('scores_json', sa.JSON(), nullable=False),
    sa.Column('weaknesses_json', sa.JSON(), nullable=False),
    sa.Column('improvements_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['resume_generations.id'], name=op.f('fk_resume_analysis_reports_generation_id_resume_generations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_analysis_reports')),
    sa.UniqueConstraint('generation_id', name=op.f('uq_resume_analysis_reports_generation_id'))
    )
    with op.batch_alter_table('resume_analysis_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_analysis_reports_id'), ['id'], unique=False)

    op.create_table('resume_designs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generation_id', sa.Integer(), nullable=False),
    sa.Column('optimized_json', sa.JSON(), nullable=False),
    sa.Column('typography_meta', sa.JSON(), nullable=False),
    sa.Column('layout_meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['resume_generations.id'], name=op.f('fk_resume_designs_generation_id_resume_generations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_designs')),
    sa.UniqueConstraint('generation_id', name=op.f('uq_resume_designs_generation_id'))
    )
    with op.batch_alter_table('resume_designs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_designs_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_designs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_designs_id'))

    op.drop_table('resume_designs')
    with op.batch_alter_table('resume_analysis_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_analysis_reports_id'))

    op.drop_table('resume_analysis_reports')
    with op.batch_alter_table('resume_generations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_generations_id'))

    op.drop_table('resume_generations')
    # ### end Alembic commands ###
