"""Add CrossReference table

Revision ID: f8be27f0e8ef
Revises: 2f7ad7435783
Create Date: 2026-07-19 18:57:36.170409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8be27f0e8ef'
down_revision: Union[str, None] = '2f7ad7435783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cross_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('consistency_score', sa.Integer(), nullable=False),
    sa.Column('credibility_score', sa.Integer(), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cross_references_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cross_references'))
    )
    with op.batch_alter_table('cross_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cross_references_id'), ['id'], unique=False)

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('cross_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cross_references_id'))

    op.drop_table('cross_references')
    # ### end Alembic commands ###
